### ISSUE TITLE
[Feature] 希望有点外卖功能

### ISSUE THREAD

**Issue by Griklit** [Miaoyww/NonsPlayer#37]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by Miaoyww** [comment]
由于NonsPlayer的核心理念，软件本体不会加入除音乐有关的任何无关内容。
如果真心想要此功能，可以前往 https://github.com/NonsPlayer/NonsPlayer-PluginStore 查看开发文档并开发属于你自己的NonsPlayer插件。
