### ISSUE TITLE
Program Crash and Temporary Playlist Disappearance with Large "Liked Music" Collection

### ISSUE THREAD

**Issue by GooGuJiang** [Miaoyww/NonsPlayer#5]
Hello,

I've encountered a few issues while using NonsPlayer. I have a large number of songs saved in my "Liked Music" list. When I attempt to access this list, the program abruptly crashes and shuts down. This has happened consistently across multiple attempts.

Further, upon restarting the program, my music collection and the playlists I've created are not visible. However, after a second restart, these playlists do reappear.

I am currently using Windows 11 Pro, version 23H2, operating system version 25393.1. The NonsPlayer version I'm using is the latest from GitHub Releases.

Even though my playlists can be restored with a program restart, this issue still impacts my user experience. I suspect that this might be due to the large number of songs I've saved in my "Liked Music" list, and could possibly be a bug when the program is handling a large volume of data.

Looking forward to your response.

Thank you,

GooGuJiang

**Comment by Miaoyww** [comment]
i have already veritied the bug, the bug will fix in the next commit, thank you for you issue

**Comment by Miaoyww** [comment]
fixed
