### ISSUE TITLE
[BUG] 首页歌单导致程序崩溃

### ISSUE THREAD

**Issue by oTnTh** [Miaoyww/NonsPlayer#52]
v0.4.1 portable，Windows 11，网易云，白嫖账号

1、首页中的所有歌单，鼠标左键单击都没有任何反应。

2、双击歌单，绝大部分情况下程序都会直接崩溃，很少部分歌单会成功进入歌曲列表。
  2.1、“每日单曲推荐”、“今天从《XXX》听起”从来没有加载成功过。
  2.2、有少部分歌单能进入歌曲列表的界面，但是看不到具体歌曲列表，然后也崩溃了。

另外还有两个问题跟标题没啥关联，一并提交在这里：

3、搜索功能不可用。

4、有部分歌播放30秒以后就停下了，我猜是需要VIP。建议提供选项，要么遇到VIP歌曲直接跳过，要么就播放30秒后直接下一首。

**Comment by Miaoyww** [comment]
release版本暂不可用，请等待最新版v0.5推送哦

**Comment by Miaoyww** [comment]
Completed at https://github.com/Miaoyww/NonsPlayer/releases/tag/0.5.0
