### ISSUE TITLE
[BUG] 无法打开程序本体

### ISSUE THREAD

**Issue by lbyisme** [Miaoyww/NonsPlayer#57]
**Describe the bug**
最新版本打不开
**To Reproduce**
1. 双击exe文件
2. 无任何界面
3. 任务管理器有后台但迅速消失
**Expected behavior**
有软件界面
**Screenshots**

https://github.com/user-attachments/assets/10cfbc60-3686-4a87-a9b7-e8522700c14a

**Desktop (please complete the following information):**
 - OS: win11 23h2
 - Version [e.g. 0.2.6]

**Comment by Miaoyww** [comment]
BUG确认，原因是位于%AppData%/Local/NonsPlayer/data目录下local_dictionaries.json的错误解析导致，稍后会推出紧急修复版本

**Comment by Miaoyww** [comment]
请下载最新release并查看是否修复问题
下次回复可能会在大约1周以后（开学了悲）
