### ISSUE TITLE
[Feature] 支持内嵌歌词

### ISSUE THREAD

**Issue by Ferry-200** [Miaoyww/NonsPlayer#67]
![image](https://github.com/user-attachments/assets/c678e769-8134-4ced-b85e-a90a0957a738)
![屏幕截图 2024-10-08 213718](https://github.com/user-attachments/assets/b262ae98-918c-402e-8ffc-379f95bef045)

关注列表的 star 里发现的，很好的项目。

related: #66 里面的第 3 点

**Comment by Ferry-200** [comment]
既然重复了我还是关闭吧

**Comment by Miaoyww** [comment]
歌词会在未来的版本重新上线
