### ISSUE TITLE
[BUG] 一些个人发现的BUG与建议

### ISSUE THREAD

**Issue by DARKNESS-ex** [Miaoyww/NonsPlayer#71]
### 1. 按钮交互BUG
    现象：正常打开以后点全屏再退出全屏，就无法操作
    可能的问题：按钮操作位置疑似未重置
https://github.com/user-attachments/assets/dca2bf91-c000-4b60-a7aa-98b6111737e3

### 2. 顶栏可进行拖动交互的范围不够
    现象：目前只有顶栏logo处可以进行拖动
    建议：全顶栏都可拖动
https://github.com/user-attachments/assets/0a37a883-f607-47f2-b689-10a0ca653d4f

### 3. 点击“我的”按钮与从歌词界面返回“我的”页面无默认操作
    现象：点击“我的”按钮与从歌词界面返回“我的”页面后不会进入首个适配器页面，而是白屏
    建议：添加默认进入"上一次进入的"适配器页面
https://github.com/user-attachments/assets/199817dc-39fe-4f9c-a3ae-10a45b3bdba0

### 4.窗口模式下歌词界面UI错误
    现象：窗口模式下歌词界面UI显示错误
    建议：添加窗口模式适配
![c364a6ad9b543924e8baed7fd638fa8e](https://github.com/user-attachments/assets/2138fbe6-9bec-40a6-bfb5-fd34925218f9)

**Comment by Miaoywww** [comment]
1. 由于未及时更新标题栏，导致标题栏所有内容均被drag区域覆盖，无法对控件进行操作。0.6版本会修复这个问题。
2. 同上，预计0.6版本会修复这个问题。
3. 很好的建议，0.6版本会同时完善"我的"-"设置"页面功能。
4. 问题已得到复现，预计在0.6版本修复。

**Comment by Miaoyww** [comment]
窗口拖动问题已在 commit `#f83fe5e` 修复
