### ISSUE TITLE
[BUG]点击歌曲界面闪退

### ISSUE THREAD

**Issue by lbyisme** [Miaoyww/NonsPlayer#72]
**Describe the bug**
点击歌曲详情页闪退
**To Reproduce**

https://github.com/user-attachments/assets/9da3337a-9c7e-4028-b975-4d26775ed3e3

**Expected behavior**
进入歌词界面
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 0.5.8]

**Comment by Miaoywww** [comment]
这里是Miaoyww的通用账号，因为在学校，用这个账号回复你。

本地音乐的歌词功能暂未完善，也没有对此做一些简单的条件判断阻止用户进入此页面。
预计0.6版本会修复此BUG，并对本地音乐做一些适配。
